bcbio/bcbio-nextgen

Dockerfile

Required to build openssl package used by anaconda.

Add bsdmainutils package to install 'hexdump' 

---

bcbio/rnaseq/dexseq.py

Newer versions of DEXSeq require the NH flag, which bwa doesn't set (see [here](http://seqanswers.com/forums/showthread.php?t=34990)).  This small workaround just turns off DEXSeq quantifications when bwa is the aligner so that the analysis doesn't crash.  This is probably a rare pipeline configuration (RNA-seq with bwa), but we do use it sometimes.

Disabled DEXSeq when the aligner is bwa.

---

docs/contents/cloud.rst

The Broad Institute is switching to direct licensing on April 16 and Appistry will no longer be involved.

Reflect new direct licensing of GATK & muTect

---

bcbio/pipeline/qcsummary.py

I ran into a minor problem where GATK was complaining about quality scores being out of bounds in certain input files.  This is in rRNA read counting in the QC steps.
I didn't dig into it too much, but it seems like GATK might be more restrictive about the spec than STAR or bwa (more [here](https://www.biostars.org/p/94637/) or [here](https://gatkforums.broadinstitute.org/discussion/2230/allow-potentially-misencoded-quality-scores-and-wrong-encoding-for-quality-scores-error)).  In this case my reads were Illumina 1.5, as verified by FastQC, and all other steps in the pipeline ran fine.  Strangely, only one out of three samples in the same run had this problem.
A quick workaround is to turn off this check for GATK, since it shouldn't matter too much here where it's just used to count …

Added GATK command line option to ignore quality score problems.

---

bcbio/variation/effects.py

I ran into a problem running small test cases that didn't have enough reads to call variants, which crashed the pipeline at effects.py line 29:
ann_vrn_file, stats_file = snpeff_effects(in_file, data)
`snp_effects` returns `None` in this case (`vcfutils.vcf_has_variants` returns `False`), which can't be unpacked to two variables.  This fix makes `snpeff_effects` always return a tuple.

Minor workaround to avoid crash when no variants are found.

---

bcbio/distributed/objectstore.py
requirements.txt

I have refactored the ```bcbio.distributed.objectstore``` in order to ease the future adding of one storage service.
For each storage service will be required one ```StorageManager``` and one ```FileHandle```.
The ```StorageManager``` is an interface which can ease the interaction with the storage service and is  exposing the following methods:
```
def check_resource(self, resource):
"""Check if the received resource can be processed by
the current storage manager.
"""
pass
def parse_remote(self, filename):
"""Parse a remote filename in order to obtain information
related to received resource.
"""
pass
def connect(self, resource):
"""Return a connection object pointing to the endpoint
associated to the received resource.
"""
pass
def download(self, filename, input_dir, dl_dir=None): …
```

Add support for Azure Blob storage service

---

bcbio/variation/varscan.py

With large data sets, errors in batches (missing tumor/normal
phenotypes) can be confusing as it's hard to find the culprit. This
commit adds the batch name to the message printed, so it's easier to
spot errors.

Show batch name when paired batch misses paired samples (VarScan)

---

bcbio/ngsalign/bwa.py

I was encountering strange errors in bwa when aligning shorter reads in Illumina 1.5 FASTQ format.  I tracked it down to bwa backtrack (`aln` + `samse` / `sampe`) and the fact that (as far as I can tell) it tries to convert the FASTQ quality scores twice.  The first time is the `-I` flag to `bwa aln`, and the second is with `seqtk -V` in `fastq_convert_pipe_cl` (in `alignprep.py`).  I'm not sure how the quality scores are encoded in the intermediate `.sai` files, but I observed that giving `bwa aln` an Illumina 1.5 file with `-I` and the subsequent `bwa samse` command an Illumina 1.9 file (the effect of the seqtk pipe, which converts based on input format) crashed bwa or gave invalid bams.
For reference, the error messages included "SEQ and QUAL are of different length" from bwa, "Invalid …

Remove obsolete -I flag from bwa aln (handled by seqtk now).

---

bcbio/structural/shared.py

to be able to detect  fusions in areas not covered by the capture bed file

Relax lumpy exclude regions

---

docs/contents/installation.rst

This fixes the package name needed to ensure the OpenSSL library and headers are installed on Red Hat systems.

Fix package name for OpenSSL library/headers on Red Hat systems

---

bcbio/graph/collectl.py
bcbio/graph/graph.py
docs/contents/cloud.rst

Now by default it pulls collectl files that fall within the range of the logfile. Otherwise it fetches an unnecessary amount of collectl rawfiles (GBs).

Add logfile and timestamp timeframe limit when processing/pulling collectl raw files

---

.travis.yml
tests/test_automated_analysis.py

This file tells Travis how to install and configure the pipeline, as well as how to run the tests.
Note though that the sole addition of this file is not enough, its also needed to:
1. Activate Travis for this repository in GitHub going to the repository settings in GitHub, Webhooks and Services, and activate Travis-CI
2. Activate the integration of this repository in [Travis-CI](https://travis-ci.org/) signing in with your account and activating `bcbio-nextgen`
Also, and this is important, since the Docker container is running the `bcbio-nextgen` code installed _inside_ the container, this is not testing the latest codebase. To do that, we should find a way of updating the code inside the container before running the testsuite. Is that something that could be easily done?
Thanks!

Add .travis.yml file for travis integration

---

docs/contents/installation.rst

`libperl-devel` doesn't exist on ubuntu (at least for 14.04), should be `libperl-dev`

Package name typo fix in docs

---

bcbio/graph/graph.py

Use the keyword "Timing" in the logs to determine if its a local or distributed run and generate the `hosts` dictionary accordingly. Ping @brainstorm .
Thanks @chapmanb and @ohofmann for the help.

Fix: Get hostname from local runs 

---

docs/contents/cloud.rst

Update some parts of AWS documentation that were, IMHO, slightly ambiguous, specifically the command to submit an analysis on a cluster with NFS FS, which was wrong, since was the same command to submit a local analysis.

Update some ambiguous part of AWS docs

---

bcbio/variation/gatkfilter.py

The typo caused the following error:
```python
Traceback (most recent call last):
File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
main(**kwargs)
File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
run_main(**kwargs)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
fc_dir, run_info_yaml)
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 241, in run
samples = run_parallel("postprocess_variants", samples)
File …
```

Fix typo in gatkfilter.py

---

bcbio/bam/fastq.py

If the first element of rand_records is high, there is a chance that it will move to the end in the first iteration of the while loop, and write only 1 read. The rest N-1 readlines will return an empty line.

Fix fastq downsampling.

---

bcbio/graph/graph.py

Thanks @guillermo-carrasco. 
@lpantano: chime in if you have any hints regarding this piece of [matplotlib code](https://github.com/brainstorm/bcbio-nextgen/blob/master/bcbio/graph/graph.py#L166):
```
top_axis.set_xticks([k for k, v in tick_kvs])
top_axis.set_xticklabels([v for k, v in tick_kvs],
rotation=45, ha='left', size=16)
```
As it is now, the xaxis `steps` annotations get overlapped on the resulting graphs :/

Reverse order of xaxis and calculate deltas accordingly.

---

docs/contents/installation.rst

The documentation report conda install -c bcbio bcbio-nextgen for a local bcbio install.
Update the local/private bcbio installation conda to bioconda in the docs.

bioconda for private bcbio installation 

---

docs/contents/installation.rst

install a local / private bcbio run in No such file or directory error (e.g.
/bin/bash: bcbio/anaconda/envs/bioconda/bin/cutadapt: No such file or directory)

fix the  No such file or directory error

---

bcbio/distributed/objectstore.py

This makes the API for objectstore file-like objects closer to the standard library file object.
It also fixes a bug when running:
`bcbio_vm.py template s3://bla.yaml s3://foo.csv`
which fails in my hands because the the S3 object is read without a size argument here: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/workflow/template.py#L131

Make size optional for objectstore file-like objects

---

bcbio/qc/multiqc.py

When kraken is enabled, variable 'm' contains a list of species and contamination percentage, which would screw up the Pandas DataFrame conversion at line 187.

Fix for error when Kraken is enabled

---

bcbio/bam/__init__.py
bcbio/bam/callable.py
bcbio/broad/metrics.py
bcbio/broad/picardrun.py
bcbio/pipeline/shared.py
bcbio/qc/qsignature.py
bcbio/structural/cn_mops.py
bcbio/structural/hydra.py
bcbio/structural/shared.py
bcbio/variation/cortex.py
bcbio/variation/joint.py
bcbio/variation/realign.py
bcbio/variation/varscan.py
scripts/utils/collect_metrics_to_csv.py

Pysam has implemented the context manager interface for quite a while
now, so the closing() calls are redundant.

Remove closing() usage around Pysam Samfile() and Fastafile().

---

docs/contents/configuration.rst

- Typo fix.
- Join lines to avoid unwanted vertical whitespace in the output.
- Mark up gvcf like the other options.

Minor documentation improvements.

---

bcbio/ngsalign/tophat.py

Small follow-up cleanup in relation to #1511 ; the (unused) list _out_fnames contained the now stale filename accepted_hits.sam.

Remove unused list _out_fnames.

---

HISTORY.md
bcbio/ngsalign/tophat.py
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml

More fixes for TopHat:
- actually use the merged BAM file (mapped + unmapped); previously the wrapper would continue with the mapped file
- fix transcriptome index file names for hg38 and hg38-noalt; previously the transcriptome indexes would be rebuilt during every TopHat run

Tophat fixes

---

bcbio/variation/mutect2.py

The code was likely copy-pasted from somewhere else, but lacked
the "items" parameter, therefore any error there would raise a NameError
because of an undefined variable.
This patch simply adds the "items" parameter, and changes the user of
the function accordingly.

Fix NameError on Mutect2 missing batches error

---

bcbio/pipeline/qcsummary.py
bcbio/qc/multiqc.py
bcbio/qc/qualimap.py
bcbio/structural/annotate.py
bcbio/structural/seq2c.py
bcbio/variation/bedutils.py
bcbio/variation/coverage.py
bcbio/variation/validate.py

Few clean-up and edge-case scenario updates before the release.
1. I reviewed caching of `clean_file()` and `add_genes()` across the pipeline and made sure that the proper prefix (like `cov-`, `svprioritize-`, `svregions-`) is provided wherever needed for correct caching. 
2. Counting genes for MultiQC: if the BED is pre-annotated, skip re-annotating and count original feature names. If we failed to annotate bed, skip reporting the count. Also handle comma-separated names and dots, and cleaning files before add_genes.
3. Reusing `clean_file()` in `seq2c.py`, cleaning redundancy in `_prep_bed()`.
4. Minor fixes and inline comments in `bedutils.py`.

Improvements in caching bed files. Fix counting genes.

---

bcbio/ngsalign/star.py
tests/unit/data.py
tests/unit/ngsalign/test_star.py

Copy all STAR output from tmpdir into workdir.
Changes:
* move all STAR action under a single `file_transaction`. Previously a part that produces `final_out` was under a file_transaction, and the rest was under `tx_tmpdir`. The output that landed into a temporary directory created by `tx_tmpdir` got lost. 
* change `out_prefix = os.path.join(align_dir, dd.get_lane(data), "star")` to  `out_prefix = os.path.join(align_dir, dd.get_lane(data))`, because that's what OncoFuse expects when looking for files
Resolves #1667 
@roryk I'd be grateful if you could do a sanity check of the fix. The main question is whether we can do `with file_transaction(data, align_dir) as tx_align_dir`. This can be done if the `align_dir` is a directory for STAR only, as it will remove whatever files there were …

Copy all star output from tmp to work dir

---

bcbio/bam/sambamba.py
bcbio/pipeline/qcsummary.py
bcbio/qc/multiqc.py
bcbio/qc/qualimap.py
bcbio/qc/samtools.py
bcbio/variation/coverage.py

Region coverage QC (completeness plot) currently checks a questionable number of depth cutoffs (1x, 5x, 10x, 20x, 40x, ... 100x, - step of 10, but skipping 30x for some reason). I find the following set of thresholds more reasonable: 1, 5, 10, 20, 50, 100, 250, 500, 1000, 5000, 10000, 50000 (high thresholds are only exposed if there is coverage at least at one sample), that what's we are used to use in TargQC, but let me know if you have another opinion.
Additionally into the text coverage files I added an extra cutoff of 80% of average coverage, which is not going to go into MultiQC, but I'm going to use it to parse in my oncology reports, hope you don't mind.
Other minor changes in this PR include:
- fix of Duplicate pct metric for RNAseq,
- expose target/genome info in MultiQC only for …

Coverage QC: thresholds for completeness plot and other updates

---

bcbio/variation/effects.py

maxentscan conda recipe installs maxentscan_score3.pl and maxentscan_score5.pl, so the executable "maxentscan" couldn't be found when called.

fixed wrong executable name for maxentscan

---

bcbio/pipeline/qcsummary.py
bcbio/qc/multiqc.py
bcbio/qc/samtools.py

Addressing @sluke123's issue with missing "Avg_coverage" metric when running with single-only reads.
Also, slightly changed the stats validation in QC: if no mapped reads are found or no reads found at all in BAM, still reporting as much coverage metrics as possible. Downstream tools may depend on `project-summary.yaml` and it's good to promise that we report those metrics even in abnormal situations.

Coverage QC fix for unpaired reads

---

bcbio/qc/variant.py

After uploaded info `final`, both `variants/bcftools_stats/%s.txt` and `variants/snpeff/%s.txt` are merged into `qc/variants/%s.txt`. This PR makes them separate.
MultiQC SnpEff module reads the sample name from the file name, and the bcbftools_stats one reads it from the contents. So it's safe to rename the bcftools file and keep the snpeff file name. Other than MultiQC, not sure if anything other downstream needs to be addressed. Given that the files are merged and no one noticed before, probably it's safe?

Variant QC upload fix

---

bcbio/variation/effects.py

Hi Brad,
Apparently, the genesplicer function called the executable dir, instead of the executable itself. An oversight which didn't come out during my testing, since the genesplicer resource seemed unavailable.
Anyways, this should fix it.
Thanks
M

VEP: fix for genesplicer plugin

---

bcbio/qc/multiqc.py
bcbio/upload/__init__.py
bcbio/upload/filesystem.py

1. Refactored the upload code a little to separate the functions that only return paths from the functions that actually upload files (e.g. `update_file` vs. `get_upload_path`)
2. Added a function that returns all paths that would to be uploaded for current run.
3. Use that function to generate `list_files_final.txt` for multiqc (partly resolves https://github.com/chapmanb/bcbio-nextgen/issues/1708)
Unfortunately that works only for the filesystem now. I don't have an infrastructure to test similar changes for other upload methods, so I hesitated with this PR. But I figured that might be a good idea to share my changes anyway so you might have suggestions and ideas, and then I or Brad or Lorena could move forward with finalising this, or rewriting, or continuing towards #1808

MultiQC: upload file list into final

---

bcbio/pipeline/qcsummary.py
bcbio/qc/multiqc.py

This PR fixes the issue of WGS runs missing the QC metrics. 
The problem is that metrics are only added if `"base"` is in the `out` dict, whereas `"base"` is added only if either `goleft indexcov` or detailed coverage is run, and both are skipped for WGS.
Plus unrelated minor fix in multiqc.

Fix coverage QC metrics for WGS

---

HISTORY.md
bcbio/variation/varscan.py

- Apply options specified in the VarScan resources config section
- Centrally apply some options common to paired/single sample calling
- Add --strand-filter in the single sample case to match paired calling
- general cleanup.

More VarScan improvements

---

docs/contents/configuration.rst

- Quote options in the example to be safe.  Not an issue here, but
specifying numeric arguments unquoted can lead to type mismatch
problems.
- Add one more option to the example to make clear how to specify
multiple options.
Specifically the vardict.py crashes with an unquoted options line like this: [-r, 2, -q, 20]

Improve resources example; fix a typo.

---

bcbio/pipeline/config_utils.py

Fractional memory specifications work in all other cases I've seen. With this they also work in e.g. the BAM to FASTQ code path.

Allow fractional memory specifications (e.g., 7.6G) in convert_to_bytes()

---

bcbio/pipeline/qcsummary.py

This allows to prevent gtf.is_qualimap_compatible() from being run. When executing several bcbio-nextgen RNA-seq runs in parallel, they all call gtf.is_qualimap_compatible(), resulting in crashes because every process tries to open the GTF DB in get_gtf_db().
Arguably we should find a solution for the concurrent DB access problem, but this works fine for now.

In the RNA-seq pipeline skip qualimap_rnaseq if qualimap was turned off.

---

bcbio/pipeline/main.py
bcbio/pipeline/run_info.py

Previously having the following snippet in the config would lead to a crash:
```
resources:
default:
```

Handle empty resource sections instead of crashing.

---

bcbio/structural/cnvkit.py

This part of CNVkit code removes dots in full file names leading to problems when a run directory name contains dots. Changing it to only remove the last dot in common prefix. Hope this is what was originally intended in this code!

Fix cnvkit issue on directory names with dots

---

bcbio/structural/cnvkit.py
bcbio/structural/seq2c.py

When running on tumor/normal pairs, Seq2C's cohort calling function returns a cut sample list containing only tumors, leading to skipping normals in downstream steps, ending with no normals in`final`. This PR fixes that.

Fix Seq2C for paired samples

---

bcbio/upload/__init__.py

Hi Brad, another minor fix for Seq2C. The `*-coverage` files it reports are not batch-level, but sample-level, so they should probably have the sample names in their files names rather than batch names. Basically that's not a big deal to just keep it as batch (it breaks postproc but easily fixable), but I figure it would be nice to correct it in bcbio.

Seq2C coverage file is not batch-level

---

bcbio/cwl/defs.py
bcbio/pipeline/main.py
bcbio/pipeline/qcsummary.py
bcbio/pipeline/run_info.py
bcbio/provenance/programs.py
bcbio/qc/multiqc.py
bcbio/qc/preseq.py
bcbio/qc/samtools.py
docs/contents/configuration.rst

Runs [`preseq lc_extrap`](http://smithlabresearch.org/software/preseq/) that estimates the yield for future experiments by showing how many additional unique reads are sequenced for increasing total read count. 
Activated by adding `preseq: true` to the `algorithm` section. I wasn't sure if it should be done using `tools_on` or with its own parameter. However, I want to add another preseq command `c_curve` for yield estimation of lower input experiments, and it would make sense to support configuration like `preseq: lc_extrap` and `preseq: c_curve`.
Reasonable prediction parameters are calculated (estimation step and limit) based on the total read count, but also configurable in `resources` section (I described it in the docs).
To aid visibility through the MultiQC plot, bcbio adds some …

Add Preseq tool for complexity prediction.

---

bcbio/qc/multiqc.py

Moving `table_columns_visible` and `module_order` settings into MultiQC_bcbio: https://github.com/MultiQC/MultiQC_bcbio/pull/14. Except for those that are set dynamically (e.g. when `qualimap` is on).
Also, `"samtools": {"error_rate": False}}` doesn't work - should be `"Samtools Stats": {"error_rate": False}}`.

Aggregate MultiQC configuration in one place 

---

bcbio/pipeline/run_info.py
bcbio/qc/preseq.py
docs/contents/configuration.rst

1. `preseq` option now accepts 2 values: `lc_extrap` and `c_curve`, each corresponding to a command of the same name. `c_curve` predicts complexity in lower input experiments. It supports the same resources parameters except `extrap` and `extrap_fraction`. 
Preseq usage in config now: `algorithm: preseq: c_curve` or `algorithm: preseq: lc_extrap`.
2. Supporting custom Preseq options in resources config, e.g. `resources: preseq: options: ["-D"]`. The override defaults and inferred best guesses.

Preseq: add c_curve and support custom options

---

bcbio/qc/multiqc.py

MultiQC:
1. upload multiqc_config.yaml into final to allow reruns.
2. support custom options in MultiQC resources (#2045), e.g.:
```
resources:
multiqc:
options: ["--cl_config", "'qualimap_config: { general_stats_coverage: [20,40,200] }'"]
```
Perhaps it makes sense to document it in `configuration.rst`, but not sure of the best way.

Multiqc config

---

bcbio/pipeline/main.py
bcbio/pipeline/qcsummary.py
bcbio/pipeline/sample.py
bcbio/qc/kraken.py

Not the most elegant solution, but since we already have a [special check](https://github.com/chapmanb/bcbio-nextgen/blob/072f90f9a803bfde1449ab80c3665fae4515c617/bcbio/ngsalign/alignprep.py#L228) for kraken to keep the ogirinal input files, I hope it doesn't look too bad to treat kraken specially in QC as well.
cc @lpantano

Kraken: do not require BAMs or aligners to run

---

bcbio/variation/effects.py

The `--af_exac` flag had been deprecated in favor of the `--af_gnomad` flags, which includes annotations of all GnomAD exome frequencies. Using the `--af_exac` flag breaks VEP, even though it's still referenced in the docs.
see ensembl/ensembl-vep#76

VEP: replaced ExAC with GnomAD

---

bcbio/pipeline/qcsummary.py
bcbio/pipeline/variation.py
bcbio/qc/multiqc.py
bcbio/qc/variant.py
bcbio/structural/manta.py
bcbio/upload/__init__.py
bcbio/variation/germline.py

- When germline calling requested for "normal" samples, write germline VCF into the "normal" results folder rather than creating a separate `<normal-sample>-germline` folder with duplicated BAM and stats.
- Run Bcftools twice, once for somatic and once for germline calls; both for the paired case (when germline calling was performed on normals), and for the single tumors (when somatic prioritization was done with the following extraction of germline variants). 
- Report both of the Bcftools runs in MultiQC (needs MultiQC PR https://github.com/ewels/MultiQC/pull/608 to be accepted).
- Remove the germline call stats from the General Stats MultiQC table, and rather report them in a separate table right above the germline Bcftools section (also needs the MultiQC PR):
Addresses the clean up …

Clean up MultiQC for germline variants calling

---

bcbio/qc/samtools.py

Hi Brad,
I took the liberty of adding a little QC step to the samtools routine. Using Idxstats in multiqc enables us to quickly check for the gender of samples based of the XY read count.
This is just a basic implementation, and I'm not sure of more steps should be added. I was hoping you could provide further plumbing if necessary.
Thanks a lot!
M

added idxstats to samtools qc step

---

bcbio/structural/__init__.py

Thanks @ohofmann for spotting the issue.
Changing `<normal>-germline` to `<normal>` lead to an issue during one of the SV callings steps where the samples are grouped by name. This part of the code wasn't run in by my test cases so it wasn't cought earlier unfortunately.
Fixing that now.

Fix uploading germline VCFs for normals

---

bcbio/structural/cnvkit.py

Line 131 in cnvkit.py calls shared.find_case_control() but `shared` module was
not imported.

Fixed missing import of bio.structrural.shared

---

bcbio/structural/metasv.py

`metasv.py` failed. After some debugging, I could see that both `call["vcf_file"]` and `call["vrn_file"]` were `None`. Therefore this line caused an exception:
`cmd += ["--%s_vcf" % call["variantcaller"], call.get("vcf_file", call["vrn_file"])]`

Ensured VCF file input for metasv.py is not None.

---

bcbio/variation/coverage.py

To address #2122 - rerun mosdepth if the coverage thresholds file is missing; if mosdepth is older, just skip processing thresholds.

Coverage thresholds checks

---

tests/integration/rnaseq/test_ericscript.py

Although a tiny fix, it helps to get all test in ` integration/rnaseq/test_ericscript.py` finish successfully :) 
The next thing is to get `CheckDB.R`  of the original `ericrscipt`  to work correctly with bcbio_nextgen bwa version. The file is in here: samtools0/share/ericscript-0.5.5-1/lib/R/CheckDB.R

Update pandas sort syntax for integration/rnaseq/test_ericscript.py

---

bcbio/setpath.py

The code in this PR addresses the first point in https://github.com/chapmanb/bcbio-nextgen/pull/2124#issuecomment-339320006 .
In this version of the `bcbio/setpath.py`, the modification to `PATH` can happen only through a function call, rather than through a side-effect of `import`.  (I will include modifications involving the actual invocations of this function in a separate PR.)

bcbio/setpath.py: initial commit

---

bcbio/qc/multiqc.py
bcbio/utils.py

Following the discussion in Slack, adding `multiqc_data.json` and cleaning up the secondary file list to get rid of globs, so it makes it more suitable for CWL definitions. Not adding changes to `cwl/defs.py` yet as I still don't have a test set up for that and don't want to break anything.
Also fixing work-rooted paths in `multiqc_data.json`, similarly to those in `list_files.txt`, to make MegaQC function out of just `final` directory.

MultiQC secondary files: add multiqc_data.json, remove globs

---

bcbio/heterogeneity/__init__.py
bcbio/qc/multiqc.py

In the `heterogeneity` module, "normal" samples get duplicated when shared between multiple batches, leading to duplicated QC work downstream. This PR regroups samples after `heterogeneity` processing, to avoid of redundant normal sample copies. Resolves duplicated QC runs for #2154

Regroup back samples after processing in heterogeneity module

---

bcbio/cwl/defs.py
bcbio/provenance/programs.py
bcbio/structural/manta.py

Hi Brad,
Adding Hartwig's BPI for Manta call filtering: https://github.com/hartwigmedical/hmftools/tree/master/break-point-inspector
Can be turned on with `tools_on: break-point-inspector`.
BPI significantly reduces the number of reported PASSed calls, 2-3 times in WGS samples that we experimented with, and we didn't spot any loss in sensitivity so far (though never actually benchmarked). Good to have it optional until we perform evaluation on a truth set, or Illumina guys consider adding it into Manta.
Needs this Bioconda PR to be accepted: https://github.com/bioconda/bioconda-recipes/pull/7061
Vlad

Add Break Point Inspector for Manta calls filtering

---

bcbio/structural/manta.py

For the samples with `germline` phenotype, `paired` object is `None`, making this piece of code crash. Adding an extra fix. Thanks @ohofmann for spotting the bug.

Fix manta+bpi for "germline" samples

---

bcbio/pipeline/sample.py

@chapmanb Not sure if other operations depend on the name in particular, but this could avoid the filename output clobbering that may be happening when cwltool is running.  Here is a proposed PR if that's the case.

Add a prefix for the variant regions to avoid filename output clobbering

---

bcbio/structural/cnvkit.py

Per issue #2267 and following up on f008e6341d207867ec0a7d4ff3d75a27269f92ad, the `--male-reference` isn't needed here, but the `--sample-sex` option can still be useful, matching the `cnvkit.py call` usage.

cnvkit diagram: Fix chrX display for male samples

---

bcbio/variation/germline.py
bcbio/variation/mutect2.py
bcbio/variation/normalize.py
bcbio/variation/strelka2.py
bcbio/variation/vcfutils.py

Currently, `min_allele_fraction` is applied to VarDict, Freebayes, Varscan, and Scalpel, but not to Mutect and Strelka2 calls. In this PR, adding support for that for the latter callers.
For Strelka2, calculating and populating `FORMAT/AF` field, which is derived from existing `AD` (germline) or `*U` (somatic snps) or `TIR` (somatic indels) FORMAT fields that represent allelic depths.
Low-AF variants are soft-filtered by adding `MinAF` into `FILTER`. Let me know if it makes sense to rather hard-filter.
Also, I figured that's not really possible to pipe filtering from the existing variant calling commands, because we can't reliably know in advance the position of the tumor sample column in VCF, so need to have VCF file saved before filtering. But that doesn't seem to add any noticeable …

Apply min_allele_fraction for Strelka2 and MuTect2 calls

---

bcbio/variation/mutect2.py
bcbio/variation/strelka2.py

Minor fix for the MinAF check. For multiallelic variants, we want to reject only those where all alleles are below the threshold.

Strelka2 and Mutect2 MinAF check: use np.all to check multiallelic

---

bcbio/structural/validate.py

When I ran SV validation for svcaller: [lumpy, manta, cnvkit, metasv, wham], the sv-validate.png plot displayed caller labels incorrectly. This is a fix of that.

A fix for SV validation plot

---

bcbio/qc/viral.py

In viral stats table, bcbio reports the number of reads supporting each GDC viral sequence. This metric doesn't take into account the size of the virus; And also, in some tests I ran into viruses that contained a small repeat that attracted thousands of reads, resulting in one colossal coverage peak, with 0 coverage all along the rest of the viral sequence.
To account for those issues, I suggest to calculate coverage completeness - e.g. % viral sequence covered at 5x - and rate the viruses based on this metric instead of read count.
Will submit a corresponding MultiQC_bcbio soon.

Viral content: calculate coverage completeness instead of read counts

---

bcbio/cwl/hpc.py

torque `qstat` has no `-j` flag, resulting in faulty tracking of job status.

CWL: cromwell torque "check-alive" fix

---

bcbio/bam/trim.py

The dollar sign in the -a atropos options (`-a 'A{200}$' -a 'C{200}$' -a 'G{200}$' -a 'T{200}$'` and the corresponding `-A` options) require the adapter to be _exactly_ 200 bases long in the read 3' end. That's not the behaviour we want: we rather want it to be of _any_ length between 8 bases and 200 bases (as soon as it in the 3' end, and not in the middle of the read!). Removing $ corrects atropos behaviour to exactly the one we want:
```
test.fq:
@read1
GGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAA
```
```
atropos trim -a 'A{200}$' --overlap 8 --no-default-adapters -se test.fq
output:
@read1
GGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAA
```
```
atropos trim -a 'A{200}' --overlap 8 --no-default-adapters -se test.fq
output:
@read1
GGGGGGGGGGG
```

Atropos polyX trimming: disable anchored mode to allow variable length polyX stretches in 3' ends

---

bcbio/structural/titancna.py

This will ensure that the right option is set with a compatible genome.
Currently the list is hardcoded as I think it is not possible to detect
those.
This fixes issue #2465.

TitanCNA: allow running with genomes with "chr" prefixes

---

bcbio/bam/callable.py
bcbio/qc/multiqc.py
bcbio/variation/coverage.py

As discussed, automatically setting thresholds when qualimap is in enabled tools.
I also had to move the `strucrual.regions` import out of the variation.coverage module to avoid circular imports `variation/coverage.py > structural/__init__.py -> structural/cn_mops.py -> structural/shared.py bam/callable.py -> variation/coverage.py`
Run a test, seems to be working.

Set qualimap multiqc coverage cutoffs based on sample depths

---

bcbio/pipeline/qcsummary.py

Often we want to see if the virus is present in a tumor sample only (which would supports its oncogenicity). How about this quick fix to check and report the viral content in normals too?

Viral check: do for normals

---

bcbio/qc/qualimap.py

rRNA stats don't show up in the MultiQC report because of broken parsing. That's how they end up in `*_bcbio.txt`:
This fixes it by stripping `\n` in the end of lines.
cc @ohofmann

Fix parsing rRNA stats

---

bcbio/qc/multiqc.py

Hi @chapmanb I was testing the test-bcbio-cwl workflows and some of them fail on rabix and SBG platform on multiqc step. I think the reason for this is because the secondary input files from some qc steps are created in subfolders relative to the primary file. When these files are mounted in the docker container in cwltool the structure is flattened, while in rabix/sbg docker containers the original structure is preserved. This modification should handle both cases. Tested with rabix and cwltool.

Fix getting input files for non-flat input structure

---

bcbio/distributed/runfn.py

Depending on the file structure for inputs, directories might be present in the same folder with primary file (which actually happens in SBG execution) but they are added with with `"class": "File"`. This fix avoids adding these directories to the secondary file list.

WIP Avoid adding directories to secondaryFiles with class File

---

bcbio/qc/variant.py

These files are not created anymore because `get_active_vcinfo`
returns an empty array instead of the first element on invocation
when running a non-ensemble setup.
Instead, it now fails 'gracefully' by attempting to find an entry for
the 'ensemble' variant caller, but if it does not find one it will still
return the first non-ensemble one.

#2618: fix qc/variants/*_bcftools file creation

---

bcbio/qc/multiqc.py

`_work_path_to_rel_final_path` should return `path` instead of `None` whenever
path is not a string, as `utils.walk_data` invocations walking over
the `multiqc` JSON data will otherwise replace all non-string (e.g.
numeric) values by `None`.

#2616: fix multiqc_data_final.json null values

---

config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-resources.yaml
config/vcfanno/GRCh37-gemini.conf
config/vcfanno/GRCh37-gnomad_genome.conf
config/vcfanno/hg38-gemini.conf
config/vcfanno/hg38-gnomad_genome.conf

Fix for GC field with multiple values in gnomad VCFs

---

bcbio/variation/effects.py

FTP is blocked by a lot HPC's due to some safety concerns, changing the URL to HTTP fixes the download issues.
Cheers
M

move VEP cache download from ftp > http

---

bcbio/structural/manta.py

1. Setting up the JVM temporary directory explicitly to avoid "No space left on device" error. Thanks @ohofmann 
2. For tumor/normal pairs, BPI was run twice on the same VCF because it was called in the loop over all samples. Add check that sample is tumor to assure it runs once.
3. Write stdout into a file because it tend to become very verbose for large datasets.

BPI clean up: 1. set tmp dir for JVM 2. avoid redundant second run

---

bcbio/variation/vardict.py

"-f" when set in `resources/vardict/options` would clash with the hardcoded "-f {freq}" defined based on `algorithm/min_allele_fraction`. 
Adding a check to avoid duplicating the option and allow overriding min_allele_fraction for VarDict.

VarDict: handle "-f" (allele freq) set in resources>vardict>options

---

bcbio/qc/multiqc.py

The work `_work_path_to_rel_final_path` does is wasteful, because it
does up to thousands of `isfile` and `isdir` calls for every path
tested.
This might make sense if the files to check are small, but not with very
large analyses.
This patch changes the behavior to take into account the fact that we're
dealing with a dictionary:
1. If the path matches the dictionary keys, fetch it immediately (O(1))
2. If the path is a file, then we have our path
3. If it is not in dictionary, it is part of a directory: select, among
the keys, *only* those that contain it
4. Of these, check if they are directories and break if a match is found
This should make the function significantly faster because it will
reduce the number of actual filesystem lookups to almost nothing.
@chapmanb  @roryk  - Please …

MultiQC: faster path lookups 

---

docs/contents/installation.rst

Sorry for that piece of irrelevance.
You referenced CloudBioLinux. I would (obviously) very much like like to bring the Debian package to a stage that it would qualify to be accepted here. At what stage would you consider adding such a reference?
Best,
Steffen

Eliminated warning for Sphinx Doc generation

---

bcbio/rnaseq/ericscript.py
docs/contents/cloud.rst
docs/contents/configuration.rst
docs/contents/installation.rst
docs/contents/parallel.rst
docs/contents/presentations.rst

@mr-c  once upon a time fixed these for the Debian package. And then these have apparently
been forgotten about.  That is the problem with 24h days.
There are ways that are past my routine git-with-github usage to adjust the author of the patch. I have cross-checked with already-bcbio-contributor Michael. He would be happy to have this patch under his name but not ultimately desparate if this arrives with my ID.

Series of spelling errors in documentation.

---

bcbio/rnaseq/gtf.py

Fixes the bug where instead of a geneid/txid pair, there was double geneid output, leading to always 0.0 rRNA rate stat.
cc @ohofmann

Fix bug in extracting rRNA features from gtf

---

bcbio/install.py

`getheader()` is no more in Python 3, use `get()` instead.

Fix urllib usage in install.py

---

scripts/bcbio_nextgen.py

The description recommends "semicolon" but should read "comma" instead.

Fix description for separators flag

---

bcbio/variation/mutect2.py

According to the GATK's doc, Mutect2 can detect read orientation
artifacts (such as stand bias caused by FFPE, or by Illumina Novaseq)
and improve results.
This is a proof of concept (completely untested at this point). In
particular this is posted for early review.
Some important points to act on:
- Do we want this on at all times (GATK says it won't hurt performance)?
- How do we make sure this is only run for paired-end samples (see
FIXME)?
- Is the current simplistic logic for file names acceptable?
This will fix issue #2846.

[PoC] Use Mutect2's new read model for filtering

---

bcbio/structural/cnvkit.py

In #2402, an (undocumented by design) option was set to allow the use of
alternative segmentation methods by CNVkit. However, the logic of
extracting configuration was swapped, thus options were never set.
For a typical YAML:
```yaml
resources:
options:
cnvkit_segment: [--drop-low-coverage, -m, hmm]
```
Before:
```python
resources = config_utils.get_resources("cnvkit_segment", data["config"])
user_options = resources.get("options", [])
```
The first option would not pick up "cnvkit_segment", but only the
fallback inside `get_resources`, so `user_options` would always be
empty.
After:
```python
resources = config_utils.get_resources("options", data["config"])
user_options = resources.get("cnvkit_segment", [])
```
And like this they are correctly set.

Fix setting CNVkit options in configuration

---

bcbio/variation/effects.py
config/genomes/BDGP6-resources.yaml
config/genomes/GRCh37-resources.yaml
config/genomes/GRCz11-resources.yaml
config/genomes/Sscrofa11.1-resources.yaml
config/genomes/WBcel235-resources.yaml
config/genomes/canFam3-resources.yaml
config/genomes/dm3-resources.yaml
config/genomes/galGal4-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml
config/genomes/mm10-resources.yaml
config/genomes/rn6-resources.yaml
config/genomes/sacCer3-resources.yaml
config/genomes/xenTro3-resources.yaml

- bump vep to v98
- added `humdiv` option to VEP, as it should be better for discovery for rare mendelian disease, see [the blog](http://www.ensembl.info/2019/10/03/cool-stuff-the-ensembl-vep-can-do-predict-pathogenicity-of-missense-variants/)
- added and reverted a dbsnp bump due to weird formatting in the dbsnp 152 vcf.
Cheers
M

bump vep resources to v98

---

bcbio/ngsalign/star.py

somehow it has been lost last time.
passes tests ok, however, fails Arriba test:
```
[2019-11-15T00:59Z] Reading chimeric alignments from '/home/ubuntu/naumenko/code/bcbio-nextgen/tests/test_automated_output/align/Test1/Test1_star/Test1.bam'ERROR: no normal reads found
[2019-11-15T00:59Z] Uncaught exception occurred
Traceback (most recent call last):
File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.9a0-py3.6.egg/bcbio/provenance/do.py", line 26, in run
_do_run(cmd, checks, log_stdout, env=env)
File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio_nextgen-1.1.9a0-py3.6.egg/bcbio/provenance/do.py", line 106, in _do_run
raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /bcbio/tools/bin/arriba -x …
```

add --twopassMode Basic to star.py

---

bcbio/cwl/hpc.py

Cromwell creates directory trees with long names, which causes torque to throw
```
qsub: -d arg is longer than 256 characters
usage: qsub [-a date_time] [-A account_string] [-b secs]
[-c [ none | { enabled | periodic | shutdown |
depth=<int> | dir=<path> | interval=<minutes>}... ]
[-C directive_prefix] [-d path] [-D path]
[-e path] [-h] [-I] [-j oe] [-k {oe}] [-l resource_list] [-m n|{abe}]
[-M user_list] [-N jobname] [-o path] [-p priority] [-P proxy_user] [-q queue] 
[-r y|n] [-S path] [-t number_to_submit] [-T type]  [-u user_list] [-w] path
[-W otherattributes=value...] [-v variable_list] [-V ] [-x] [-X] [-z] [script]
```
`cd`-ing to the directory beforehand fixes this.
Cheers
M

remove directory param from torque qsub

---

config/genomes/BDGP6-resources.yaml

Hi,
here my PR to add support of miRNA analysis with BDGP6 genome.
Related to this [bcbio issue #3112 ](https://github.com/bcbio/bcbio-nextgen/issues/3112) and PR to the cloudbiolinux https://github.com/chapmanb/cloudbiolinux/pull/344

add support of miRNA data to BDGP6

---

config/genomes/BDGP6-resources.yaml

Fixing the bug indentations preventing the execution of smallRNA-seq analysis for BDGP6 (see [this comment of issue #3112 ](https://github.com/bcbio/bcbio-nextgen/issues/3112#issuecomment-594697863))

Fix indentations in srnaseq resources of BDGP6

---

bcbio/heterogeneity/loh.py

The current code did not check if the copy number values were valid
(some can be NA) and thus it would error out when trying to coerce them
with a float.
The easiest solution, since bcbio already depends on pandas, was to
ditch the custom parsing and use pandas to read the file, and skip lines
with missing values.
As a micro optimization, reading the LOH file was put outside the loop,
to reduce needless I/O.

Fix generation of PureCN summary output

---

bcbio/pipeline/run_info.py

We're getting the error below. I'm pretty sure this is another issue caused by the python2 → python3 upgrade, but maybe undetected so far because people didn't make the same parameter mistake we did. So I just skip sorting the `allowed` list to fix.
```
Checking sample YAML configuration: /whatwhat/something_bcbio.yaml
Traceback (most recent call last):
File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
main(**kwargs)
File "/opt/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
run_main(**kwargs)
File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
fc_dir, run_info_yaml)
File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
for xs in pipeline(config, run_info_yaml, …
```

Cannot sort [str, str, str, None, bool] in python3

---

scripts/bcbio_nextgen_install.py

Toward #3191:
* make bcbio_nextgen_install.py PEP8 compliant
* remove unused code from install_conda_build()
* remove unnecessary error handling around import of argparse module

Installer cleanup

---

docs/contents/installation.md

There is no `scripts/vm` directory anymore and `Vagrantfile` is at the top level.

Fix VM installation instructions and remove Python 2.6 from requirements

---

bcbio/qc/viral.py

Added the read count and read percentage mapped to a virus, to address the request at https://github.com/bcbio/bcbio-nextgen/issues/3154
I also added some required `setuptools.setup()` parameters at `setup.py` to enable installation with pip, it really helps with development. Hope it doesn't break anything.

Viral content: add read counts

---

docs/contents/installation.md

This PR makes the command line consistent with the explanation below. This seems to have diverged [long time ago](https://github.com/bcbio/bcbio-nextgen/commit/aa123a2772546a592b80246bf1d6bb0a547ce86f#diff-8588fd730c01761623042ab6a9660c12L12).

Make installation instructions consistent

---

scripts/bcbio_nextgen_install.py

* Specify exact Miniconda version in the installer to prevent issues like #3240 
* Simplify installer code (toward #3191)
* Update Conda repo URL

Prevent silent updates of Miniconda during installation

---

bcbio/structural/gatkcnv.py

when I generated a gatk-cnv pon.hdf5 with
https://bcbio-nextgen.readthedocs.io/en/latest/contents/somatic_variants.html#workflow3-somatic-tumor-only-cnvs
and passed it to call CNV in tumor, it failed due to b'chr1' in chromosome names
related to #3227

fix encoding error when decoding pon.hdf5 from gatkcnv

---

bcbio/cwl/create.py

resources.yaml is required to be included as secondary files in order to run the postprocess_alignment_to_rec and prep_samples_to_rec steps

Corrected the omission of *-resources.yaml

---

.github/ISSUE_TEMPLATE/bug_report.md

To help with poorly formatted bug reports

Add formatting hints to the GitHub issue template

---

.gitignore
.travis.yml
docs/contents/development.md

No need to add [skip ci] or similar to avoid starting CI builds if only Markdown files were changed.

Skip Travis CI builds if only Markdown files were changed

---

.gitignore
docs/contents/development.md
scripts/vagrant.sh
tests/bcbio_vm/test_docker.py
tests/conftest.py
tests/integration/rnaseq/test_ericscript.py
tests/integration/test_S3_pipelines.py
tests/integration/test_automated_analysis.py
tests/integration/test_pipeline.py

Add `--keep-test-dir` option to close #3155. Simplify test configuration. Move test output directory outside the source tree.

Add option to preserve test output dir between test runs

---

bcbio/heterogeneity/loh.py

This warning popped up while testing the Debian package.

heterogeneity/loh.h: SyntaxWarning: "is not" with a literal. Did you mean "!="?

---

bcbio/structural/__init__.py
bcbio/structural/scramble.py
bcbio/upload/__init__.py

Toward #3244. This depends on https://github.com/chapmanb/cloudbiolinux/pull/369 and requires SCRAMble to be installed using Conda.
The following project config file was used for testing:
```
upload:
dir: ../final
details:
- algorithm:
aligner: false
bam_clean: remove_extracontigs
svcaller: [scramble]
variantcaller: false
analysis: variant2
description: test1
files: [../input/test.bam]
genome_build: hg38
- algorithm:
aligner: false
bam_clean: remove_extracontigs
svcaller: [scramble]
variantcaller: false
analysis: variant2
description: test2
files: [../input/test2.bam]
genome_build: hg38
- algorithm:
aligner: false
bam_clean: remove_extracontigs
svcaller: [scramble]
variantcaller: false
analysis: variant2
description: test3
metadata:
batch: batch1
files: [../input/test3.bam]
genome_build: …
```

SCRAMble integration

---

bcbio/chipseq/macs2.py

Fixing the bug where the value of the `antibody` column is not within the list, no peaks are called.
**We want to run narrow peak calling (by default) if antibody is not recognized.**, as discussed with Shannan.
- Note that If there is no `antibody` column, narrowpeak call is called by default.

update default peak calling for antibody

---

docs/contents/atac.md

after fixing the macs2.py, we will start callling narrow peaks even if invalid antibodies are in the `antibody` column of the metadata.

Update after updating the macs2.py

---

bcbio/structural/purecn.py

Unlike run_purecn_normaldb, run_purecn was never adjusted.

Adjust paired PureCN to the new way of locating PureCN.R

---

scripts/bcbio_nextgen_install.py

conda 4.13.0 is now available and [breaks older versions of mamba](https://github.com/mamba-org/mamba/issues/1724).
I see https://github.com/bcbio/bcbio-nextgen/issues/3614 and commit https://github.com/bcbio/bcbio-nextgen/commit/960bcd1f0deb8de1062f93c50dd6de4d1d287b49 where the mamba version has been pinned.
This pull request simply bumps the mamba version to current 0.24.0. This tactic has succeeded in my environment.

Bump pinned mamba version

---

bcbio/ngsalign/bwa.py
bcbio/utils.py
bcbio/variation/vcfutils.py
docs/contents/purecn.md

There are small typos in:
- bcbio/ngsalign/bwa.py
- bcbio/utils.py
- bcbio/variation/vcfutils.py
- docs/contents/purecn.md
Fixes:
- Should read `successful` rather than `successfull`.
- Should read `file` rather than `fils`.
- Should read `tumor` rather than `turmor`.
- Should read `occurrences` rather than `occurances`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

docs/contents/atac.md

The previous version had an extra new line with broad and narrow on separate sides of the new line character and it was a bit confusing.

Split up broad and narrow antibodies
