bcbio/bcbio-nextgen

docs/contents/introduction.rst

Added a blurb about our lab to the users page.

Added paragraph about Gifford lab at MIT CSAIL.

---

tests/data/illumina_samplesheet.csv

Close quotation

---

docs/contents/introduction.rst

As the title says. In the interest of full disclosure, I'm the first author of said paper, and Brad is a co-author.

Add the paper published in Annals of Oncology in 2015 to the Mario Negri part of the User section

---

bcbio/graph/graph.py

The files which contain information will be parsed in [bcbio.graph.resource_usage](https://github.com/alexandrucoman/bcbio-nextgen/blob/refactor/graph/bcbio/graph/graph.py#L250-L288) or another function and [generate_graph](https://github.com/alexandrucoman/bcbio-nextgen/blob/refactor/graph/bcbio/graph/graph.py#L291-L292) will receive [the ouput](https://github.com/alexandrucoman/bcbio-nextgen/blob/refactor/graph/bcbio/graph/graph.py#L365-L372) in order to plot the graphs.
This patch can be required by another cloud providers which have the resource usage information stored in another format.
Thanks,
Alex

Refactor bcbio.graph.graph.generate_graph

---

config/bcbio_system.yaml

I propose the inclusion of the matters discussed in https://groups.google.com/forum/#!topic/biovalidation/R0-zqi55TMI in order for those things to be documented somewhere in the code.
Please correct the new sentences as needed (content, grammar).

Extended explanation of memory and cores

---

docs/contents/parallel.rst

Further doc changes according to the discussions at https://groups.google.com/forum/#!topic/biovalidation/R0-zqi55TMI
Before accepting please revise the correctness of content & grammar.
Thanks,
Michael

Memory and parallelization optimizations in doc

---

bcbio/distributed/objectstore.py

Fixes chapmanb/bcbio-nextgen-v#92

Remove extra argument passed to FileHandle.__init__

---

bcbio/ngsalign/novoalign.py

replace samtools placeholder with path in novoalign cmd

---

bcbio/graph/graph.py

Goes together with PR: https://github.com/chapmanb/bcbio-nextgen-vm/pull/118
* Shows/plots graphs on a jupyter notebook if running from it.
@guillermo-carrasco, this one should get merged too in order for the serialization/jupyter notebook to work.

Serialize at graph pre-plot stage

---

bcbio/graph/graph.py

Collectl plots

---

bcbio/graph/graph.py

https://github.com/chapmanb/bcbio-nextgen-vm/pull/120
@guillermo-carrasco Heads up on this one for your current 2 runs...

Serialize graph info from before mangling/plotting for third party plotting libs

---

docs/conf.py
docs/contents/code.rst
docs/contents/configuration.rst
docs/contents/installation.rst
docs/contents/outputs.rst
docs/contents/parallel.rst
docs/contents/pipelines.rst
docs/contents/sequencer.rst
docs/contents/testing.rst
requirements.txt
tests/run_tests.sh

While reading the docs, I found these minor things that could be changed.
Excellent software documentation, by the way :-)

Some docs amendments 

---

bcbio/variation/vardict.py
docs/contents/configuration.rst

Yo Brad,
This pull request will help us run paired VarDict bare, without any of the paired filtering. Should be used with caution.

Vardict paired germline

---

bcbio/pipeline/disambiguate/__init__.py
bcbio/pipeline/disambiguate/run.py

To be tested further, but essentially provides the same tags as tophat2 out of the box.

Hisat2 to use Tophat disambiguation algorithm

---

bcbio/distributed/objectstore.py

The current version of the BlobHandle doesn't act properly when
a user tries to read a file from Azure Blob chunk by chunk.
Thanks,
Alex

Fix the BlobHandle read file issue

---

config/templates/illumina-chipseq.yaml
docs/contents/configuration.rst

adapted this based on most recent run of bcbio chipseq

changed the template for chip-seq analysis

---

bcbio/rnaseq/cufflinks.py

Hello!
Just a small bugfix: cufflinks assemble does not currrently use library-type option. Unless used  the right option on the stranded data the following error occurs:
BAM record error: found spliced alignment without XS attribute

Cufflinks assembling should take library type into count.

---

docs/contents/cloud.rst

Just a short explanation on how to extract the pandas dataframes from the pickled file.

Add serialize functionality example usage and plotting.

---

bcbio/graph/graph.py

Better looking collectl plots. Fix Y axis for network plots to easily compare.

---

bcbio/pipeline/disambiguate/run.py

Symptom of bwakit on ALT alignments

Ignore AS tag if not present

---

bcbio/ngsalign/tophat.py

- Remove unneeded closing()
- Utilize "with" in one more instamce
- Update a comment to reflect which TopHat versions are buggy

Cleanups in the Tophat wrapper

---

bcbio/variation/effects.py

Added gene_phenotype flag to VEP analysis, as this info is valuable in a diagnostics settings

Added gene_phenotype flag to VEP analysis

---

bcbio/pipeline/disambiguate/run.py
bcbio/rnaseq/oncofuse.py

- Use "with" to safely open files
- Use Pysam's API to check read flags

Further cleanups

---

bcbio/galaxy/loc.py
bcbio/ngsalign/rapmap.py
bcbio/rnaseq/umi.py
bcbio/server/run.py
bcbio/variation/bamprep.py

These are mostly accesses to undefined variables.  I have changed these
to what seems to make sense from my reading of the code, however I have
not tested them!
Given that the existing code cannot possibly work, these changes at least
shouldn't make things worse :-)

Fix various issues flagged by PyFlakes.

---

docs/contents/configuration.rst
docs/contents/outputs.rst
docs/contents/pipelines.rst

- typos and language improvements
- add tophat2 and hisat2 to the list of aligner options

Minor documentation fixes

---

bcbio/variation/population.py

GEMINI only supports hg19/GRCh37 for now, don't try to build DBs for other assemblies.

GEMINI supports only human genome build hg19/GRCh37 for now.

---

bcbio/ngsalign/tophat.py

Currently the "missing 0x8 bit" problem that unmapped.bam files have
is fixed using a home-grown solution.  Instead, use TopHat-Recondition,
which fixes this problem as well as two additional problem classes.
The issues are described in detail here:
Homepage:  https://github.com/cbrueffer/tophat-recondition
Publication   http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1058-x
Since this requires an external program, how to ensure it is installed (it is available through bioconda)? Is cloudbiolinux contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml the right place?

When running TopHat, use TopHat-Recondition to fix the unmapped.bam file.

---

docs/contents/pipelines.rst

I corrected some of the links that were broken.

Fixing Links

---

bcbio/variation/effects.py
config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml

fixes botched commit history from #1659

made dbNSFP fields modifiable, added dbNSFP for hg38

---

bcbio/variation/effects.py

As discussed in #1665 
I think this should do the trick?
Thanks
M

source alternate dbsnfp fields from bcbio_system.yaml

---

docs/contents/pipelines.rst

see https://github.com/chapmanb/bcbio-nextgen/issues/1575#issuecomment-265565185

document fastrna-seq

---

config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml

To be merged after issues with recipe for v87 are resolved
bioconda/bioconda-recipes#3177

updated vep cache version

---

config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml
docs/contents/installation.rst

related to chapmanb/cloudbiolinux#238

added genesplicer to config, updated docs for dbscSNV

---

bcbio/bam/sambamba.py
bcbio/pipeline/qcsummary.py
bcbio/qc/multiqc.py
bcbio/qc/samtools.py

Brad,
Following our email discussion, starting a PR for coverage QC optimisation in WGS. The first commit is to skip padded coverage QC calculation.  Will continue trying to remove redundant sambamba/samtools runs.

Coverage QC optimisation for WGS

---

bcbio/upload/__init__.py
bcbio/upload/irods.py
docs/contents/configuration.rst

I messed up my git history in the other PR, so here's a new one!
This one is as good as ready, but I'm still struggling with the filenames.
@schelhorn?

added iRODS upload module, currently without support for metadata

---

docs/contents/configuration.rst

Sorry, I seem to have missed these during my code review

fixed some typos and missing info in the docs

---

bcbio/upload/irods.py
docs/contents/configuration.rst

switch upload command from `iput` to `irsync`, which seems more dependable.
removed unused code and functions.

cleaned up iRODS upload code, switched upload approach

---

bcbio/variation/multiallelic.py

fix for vcf2db warning messages

---

scripts/ansible/README.md
scripts/ansible/ansible.cfg
scripts/ansible/launch_aws.yaml

Solves ansible bootstrapping problems on new Ubuntu and unix socket issues:
https://github.com/ansible/ansible/issues/11536#issuecomment-120092814
https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found#34402816

First successful ubuntu 16.10 aws ansible run

---

bcbio/variation/population.py
docs/contents/configuration.rst

as discussed in #1573, added `--expand` flags to vcf2db command
M

added expand flag to vcf2db command

---

bcbio/qc/qualimap.py

- A small fix in Qualimap files uploading in order to make MultiQC happy when displaying sample names in Qualimap plots.

Qualimap file upload improvements

---

bcbio/structural/seq2c.py

Thanks for being ahead of me Brad in this! 
A minor fix from me, to avoid overriding the options in case of presence of normals. This won't affect Marisa's and Sally's case as they use -E for germline, but good to have this fix anyway.

Seq2C custom options fix

---

docs/contents/configuration.rst
docs/contents/parallel.rst

Corrects the mark_duplicates description and fixes typos.

Documentation improvements

---

bcbio/ngsalign/hisat2.py
bcbio/rnaseq/variation.py
docs/contents/configuration.rst

Also clarify the docs a little.

Honor additional options for hisat2 and VarDict in the RNA-seq workflow

---

config/vcfanno/hg38-gemini.lua

updated ESP AF calculation

---

docs/contents/configuration.rst

add documentation on problem with sequentially numbered samples

update config docs PE auto config

---

bcbio/variation/effects.py

added missing comma in the VEP args list

VEP: fixed typo

---

bcbio/variation/vcfanno.py
config/vcfanno/hg38-gemini.lua

fix by @brentp https://github.com/brentp/vcfanno/commit/5fcce8db2aeee016ab927c8ca36a715c02f982f9
fixes a whole bunch of error messages from vcfanno.

fixes for vcfanno/vcf2db error messages

---

bcbio/variation/effects.py

Added support for new SpliceRegion plugin
Plugin file already added to conda recipe.
Cheers
M

VEP tweaks

---

bcbio/structural/__init__.py

One more fix for that. Address the scenario of ensemble SV calling + tumors sharing one normal + germline calling for normal.

Fix SV ensemble batching with germline sample (#2111 part 2)

---

bcbio/setpath.py
scripts/bcbio_nextgen.py

The code in this PR addresses the first point in https://github.com/chapmanb/bcbio-nextgen/pull/2124#issuecomment-339320006 .
(NB: this PR extends #2128.)

Invoke prepend bcbiopath

---

config/genomes/GRCh37-resources.yaml
config/genomes/GRCz10-resources.yaml
config/genomes/WBcel235-resources.yaml
config/genomes/canFam3-resources.yaml
config/genomes/dm3-resources.yaml
config/genomes/galGal4-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml
config/genomes/mm10-resources.yaml
config/genomes/rn6-resources.yaml
config/genomes/sacCer3-resources.yaml
config/genomes/xenTro3-resources.yaml

Small update for the new ensembl release
Merge pending conda recipe update, there's no github release of VEP yet.
I'll update when the conda recipe is available
Cheers
M

ensembl 91: updated genome resources

---

config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml
docs/contents/installation.rst

fixes https://github.com/chapmanb/cloudbiolinux/issues/262
Docs may need some more work to fit with the rest.
Ping @lemdcock
Cheers
M

made cosmic ref file name more generic, added pointer for hg38, docs

---

HISTORY.md
bcbio/pipeline/qcsummary.py
docs/contents/configuration.rst

This allows to skip running `samtools-stats`

Add `coverage_qc` to `tools_off`

---

bcbio/cwl/hpc.py

removed invalid flags from cromwell torque job submission config

cromwell: torque qsub fix

---

docs/contents/cwl.rst

Hopefully this will be heads-up if someone tries to run the install commands on MAC or any other platform

Clarifying the OS expectation for the mentioned bcbio-vm install commands

---

scripts/bcbio_nextgen.py
scripts/bcbio_setup_genome.py
tests/integration/test_pipeline.py

python3 transition - print lacked ()s

---

scripts/bcbio_setup_genome.py

I should have rebased the changes over here and not work with the web interface. Hope you don't mind too much.

Eliminated "print >>" for python3

---

bcbio/structural/titancna.py

According to the documentation
(https://github.com/gavinha/TitanCNA/tree/master/scripts/R_scripts) the
model needs different parameters depending on variance in read data and
depending on the data type.
This commit adds the two recommended parameters for non-WGS runs.

TitanCNA: use correct parameters for WES runs

---

config/genomes/GRCh37-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml

Updates for clinvar/dbSNP
This makes sure the versions in the VEP cache and the resources are more aligned
ref:https://github.com/chapmanb/cloudbiolinux/pull/273
Cheers
M

updated genome resources for dbSNP, clinvar

---

bcbio/cwl/hpc.py

Update bcbio/cwl/hpc.py with support to lsf

---

config/vcfanno/GRCh37-gemini.conf
config/vcfanno/GRCh37-gnomad_exome.conf
config/vcfanno/GRCh37-gnomad_genome.conf
config/vcfanno/hg38-gemini.conf
config/vcfanno/hg38-gnomad_exome.conf
config/vcfanno/hg38-gnomad_genome.conf

ref #2570 
As promised, the configs needed for gnomAD exome. I've only added stuff. I'll leave removing up to you.
I tried to keep the annotations from gnomAD as similar as possible to the existing ExAC ones, without having to use any postannotations, as all data is present in the vcf.
Cheers
M

gnomAD exome config

---

bcbio/distributed/runfn.py

Update for #2599
Extend the check to all cases where secondaryFiles are populated.

Extend check for directory in secondaryFiles

---

bcbio/install.py

install.py: fix typo

---

bcbio/srna/mirdeep.py

Addresses https://github.com/bcbio/bcbio-nextgen/issues/2762

Add -g -1 option to prevent early exit in mirdeep2

---

bcbio/broad/__init__.py

GATK3 version check fix

---

docs/contents/code.rst

Update dev infrastructure instructions

---

bcbio/ngsalign/postalign.py
bcbio/pipeline/datadict.py
bcbio/pipeline/run_info.py
bcbio/variation/vardict.py

low frequency somatic variants with vardict. Addressed code review

introduced use_lowfreq_filter: false yaml option to allow calling of

---

bcbio/variation/effects.py

to fix https://github.com/bcbio/bcbio-nextgen/issues/2991

fixed VEP installation path pointing to indexed_vep_cache in v.98

---

bcbio/variation/effects.py

https://github.com/bcbio/bcbio-nextgen/issues/2993

fixed a bug in variation/effects/vep

---

bcbio/broad/picardrun.py
bcbio/pipeline/sample.py

addresses https://github.com/bcbio/bcbio-nextgen/issues/3000

fix picard_reorder call

---

bcbio/pipeline/sra.py
scripts/bcbio_prepare_samples.py

related to https://github.com/bcbio/bcbio-nextgen/issues/3015

fix SRR downloading

---

bcbio/broad/__init__.py

Fix simple typo: whwere -> where

---

.gitignore
tests/conftest.py
tests/integration/test_automated_analysis.py

Fix automated analysis integration test

---

scripts/utils/plink_to_vcf.py

Clean up plink_to_vcf.py and make it Python 3 compatible

---

setup.cfg
setup.py

Add and move package metadata to `setup.cfg`. Simplify `setup.py`.
See https://test.pypi.org/project/bcbio-nextgen/1.2.0/ for resulting changes.

Update Python package setup

---

bcbio/pipeline/main.py

Since joint calling is inherently single threaded, let the scheduler only request one core and submit more jobs.

improve parallelization of joint calling

---

bcbio/pipeline/run_info.py
config/examples/NA12878-exome-methodcmp.yaml

variant_regions do not seem to be validation target
close #3126

fixes enty use case

---

README.md

https://docs.readthedocs.io/en/stable/badges.html

Add doc build status badge

---

.github/ISSUE_TEMPLATE/bug_report.md

The minimum information required to troubleshoot issues.
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

Add a bug report template

---

Dockerfile
bcbio/install.py
bcbio/ngsalign/mosaik.py
bcbio/workflow/template.py
config/examples/NA12878-exome-methodcmp-getdata.sh
docs/contents/intro.md
scripts/ansible/README.md
scripts/bcbio_nextgen_install.py

raw.github.com permanently redirects to raw.githubusercontent.com

Change raw.github.com URLs to raw.githubusercontent.com

---

bcbio/qc/multiqc.py

close #3139 
thanks @vladsaveliev!

fix duplicated rows in the multiqc report

---

bcbio/qc/qualimap.py

fix salmon input for rRNA calculation

---

bcbio/bam/cram.py
tests/data/automated/run_info-variantcall.yaml

xref #3107 
Feel free to comment/edit/request changes
Cheers
M

covert bam squeeze/samtools compression to scramble

---

tests/bcbio_vm/test_docker.py
tests/conftest.py

Enable running CWL tests in Vagrant and cleanup CWL tests

---

bcbio/install.py
docs/contents/installation.md
scripts/bcbio_nextgen_install.py

Toward #3191:
* Configure Conda channels via .condarc configuration file
* Remove _get_conda_channels() and install_conda_build()
* PEP8 fixes

Conda install cleanup

---

bcbio/rnaseq/salmon.py

Possible fix for #3235

---

scripts/bcbio_nextgen_install.py

Update Python to version 3.7 in the installer

---

bcbio/bam/fastq.py

close #3277 and biopython/biopython#3015

fix SeqIO handle in bam/fastq

---

docs/contents/installation.md

Update requirements for tool installation and data upgrade.

Resource requirements

---

docs/contents/somatic_variants.md

Document remove_lcr parameter

---

.travis.yml

Reduce progress reporting by wget from almost 2K lines to 3 lines.

Reduce output from wget in Travis CI logs

---

bcbio/ngsalign/bismark.py
bcbio/qc/multiqc.py

introduces bismark_threads and bowtie_threads to bismark resources.
16/2 gives a dramatic performance boost

bismark and bowtie2 parallelization

---

config/bcbio_system.yaml

from 3G to 4G / core. save ppl from segfaults

increase default RAM

---

bcbio/variation/effects.py
config/genomes/BDGP6-resources.yaml
config/genomes/GRCh37-resources.yaml
config/genomes/GRCz11-resources.yaml
config/genomes/Sscrofa11.1-resources.yaml
config/genomes/WBcel235-resources.yaml
config/genomes/canFam3-resources.yaml
config/genomes/dm3-resources.yaml
config/genomes/galGal4-resources.yaml
config/genomes/hg19-resources.yaml
config/genomes/hg38-noalt-resources.yaml
config/genomes/hg38-resources.yaml
config/genomes/mm10-resources.yaml
config/genomes/rn6-resources.yaml
config/genomes/sacCer3-resources.yaml
config/genomes/xenTro3-resources.yaml

Reverts bcbio/bcbio-nextgen#3352

Revert "Update/vep102"

---

bcbio/pipeline/main.py
bcbio/pipeline/run_info.py
bcbio/pipeline/sample.py
bcbio/structural/__init__.py
bcbio/structural/purecn.py
bcbio/structural/regions.py
bcbio/upload/__init__.py
bcbio/utils.py
bcbio/variation/gatk.py
bcbio/variation/multi.py
bcbio/variation/mutect2.py
bcbio/variation/population.py
bcbio/variation/vcfutils.py

- prepare purecn bed file
- calculate purecn coverage
- purecn rscript wrappers
- run purecn without gatk-cnv and cnvkit segmentation
- update mutect variant calling when creating SNV PON
- correct batch pairing logic to allow PON processing
- merge SNV pon
- normal db creation and upload to final
- PON creation works, passes cancermulti
- T-only + PON works
- t/n calling + pon works
- standard production pipeline works
- bug fixes

PureCN analysis support in bcbio:

---

bcbio/structural/__init__.py
bcbio/structural/purecn.py

PureCN can and will work fine also with hg19.

Drop hardcoded hg38 requirement in PureCN

---

MANIFEST.in
bcbio/pipeline/rnaseq.py
bcbio/scripts/R/bcbio2se.R
bcbio/scripts/R/se2qc.Rmd
bcbio/upload/__init__.py

fix bcbio2se and add se2qc in bulk rna-seq

---

bcbio/pipeline/qcsummary.py

since verifybamid2 hangs on AWS instances

add tools_off: contamination option

---

bcbio/ngsalign/bismark.py
bcbio/upload/__init__.py

use --local and --maxins 1000 as default alignment settings

wgbs: upload sorted bam as output

---

docs/contents/atac.md

Corrected final version for the user story.
The metadata has use for `antibody` column which is pretty major.
- It changes how the peaks are called (narrow, broad, or none)

Updating the metadata.

---

scripts/bcbio_nextgen_install.py

mamba was added as default in the mid-2020 and worked fast : 30 min vs 20 hours.
1.2.8 installs with mamba are stalling, conda works fine; 
conda is now default, with --mamba option to switch on mamba

set conda installer by default and add --mamba as an option

---

bcbio/ngsalign/bowtie2.py

in chip-seq, for bowtie2, we changed '--very-sensitive' -> '--very-sensitive-local' to softclip.
This has been discussed with Rory and Meeta.
We can wait for Shannan to confirm this change.
Will update in slack for the pull-request.

Update softclipping for chipseq

---

bcbio/provenance/programs.py

add tracking 4 more rna-seq related tools in programs.txt

---

bcbio/broad/__init__.py
bcbio/broad/metrics.py
bcbio/broad/picardrun.py
bcbio/variation/gatk.py

fix picard options to --option value

fix picard calls to work when gatk4 is off

---

bcbio/rnaseq/bcbiornaseq.py

yes, it is YYYY-MM-DD not the actual date, should be fixed in r-bcbiornaseq 0.3.44

update bcbiornaseq template name and rds path workaround

---

config/examples/NA12878-hg38-validate.yaml
config/examples/NA12878-sv.yaml
config/examples/NA12878-trio-wgs-joint.yaml
config/examples/NA12878-trio-wgs-validate.yaml
config/examples/NA24385-10x.yaml
config/examples/cancer-dream-syn3.yaml
config/examples/cancer-dream-syn4.yaml
config/examples/giab-validate.yaml
config/teaching/cancer-syn3-chr6.yaml
config/templates/somatic_tumor_only.yaml
docs/contents/disambiguation.md
docs/contents/somatic_variants.md

retire remove_lcr: true

---

scripts/bcbio_nextgen_install.py

fix installation to avoid downgrading mamba

---

bcbio/variation/peddy.py

run gvcf2vcf on the fly for peddy when tools_on: gvcf

---

scripts/bcbio_setup_genome.py

Fixes the following issue: https://github.com/bcbio/bcbio-nextgen/issues/3689
The problem originated from this commit: https://github.com/bcbio/bcbio-nextgen/commit/d61e77825f46548101db9b64776269f8e96ee220

Add --cloudbiolinux argument
